/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'chart';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String AVATER1 = 'assets/images/avater1.png';
  static const String S1 = 'assets/images/s1.png';
  static const String S2 = 'assets/images/s2.png';
  static const String S3 = 'assets/images/s3.png';
  static const String SPEECH_BUBBLE = 'assets/images/speech_bubble.png';
  static const String SPLASH = 'assets/images/splash.jpeg';
  static const String AR_EGY = 'assets/translations/ar-EGY.json';
  static const String EN_US = 'assets/translations/en-US.json';
}
