/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String INTER_BOLD = 'Inter-Bold';
  static const String INTER_MEDIUM = 'Inter-Medium';
  static const String INTER_REGULAR = 'Inter-Regular';
  static const String INTER_SEMIBOLD = 'Inter-SemiBold';
  static const String LEXEND_BOLD = 'Lexend-Bold';
  static const String LEXEND_MEDIUM = 'Lexend-Medium';
  static const String LEXEND_REGULAR = 'Lexend-Regular';
  static const String LEXEND_SEMIBOLD = 'Lexend-SemiBold';
  static const String OPENSANS_BOLD = 'OpenSans-Bold';
  static const String OPENSANS_REGULAR = 'OpenSans-Regular';
  static const String OPENSANS_SEMIBOLD = 'OpenSans-SemiBold';
  static const String OXYGEN_BOLD = 'Oxygen-Bold';
  static const String OXYGEN_LIGHT = 'Oxygen-Light';
  static const String OXYGEN_REGULAR = 'Oxygen-Regular';
  static const String SEGOE_BOLD = 'Segoe-Bold';
  static const String SEGOE_REGULAR = 'Segoe-Regular';
}
